### ISSUE TITLE
[FEATURE] Generate openapi `components`

### ISSUE THREAD

**Issue by burich85** [explyt/spring-plugin#10]
### Problem details

OpenAPI

### Describe the problem

We are able to generate endpoints now, but `$ref` could use `component` that doesn't created yet

### Describe the solution

On adding `$ref` to an openapi description, check if `component` with the same name exists. If it doesn't exist, generate it from class

```yaml
items:
  $ref: '#/components/schemas/Task'
```

=>

```yaml
components:
  schemas:
    Task:
      type: object
      description: Task
      required:
        - name
      properties:
        name:
          description: name
          type: string
        code:
          description: code
          format: string
```

### Additional context

Could we also update existing one? 
Should we add some meta-info to handle elements renamed by user?
